# Stage 1: Build the Vite React application with Node.js 22
FROM node:22
WORKDIR /app
ARG PORT
ARG MONGO_URL
ARG FLEETX_USERNAME
ARG FLEETX_PASSWORD
ARG FLEETX_TOKEN

ENV PORT=$PORT
ENV MONGO_URL=$MONGO_URL
ENV FLEETX_USERNAME=$FLEETX_USERNAME
ENV FLEETX_PASSWORD=$FLEETX_PASSWORD
ENV FLEETX_TOKEN=$FLEETX_TOKEN

COPY package.json package-lock.json ./
RUN npm install
COPY . .
EXPOSE 7000
CMD ["npm","run","dev"]
